function Hd = RRC_gen(Fs,N,Fc,R)
%RRC_GEN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 29-Nov-2017 14:11:01

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are in kHz.
% Fs = 76.8;  % Sampling Frequency

% N    = 192;        % Order
% Fc   = 2.4;        % Cutoff Frequency
TM   = 'Rolloff';  % Transition Mode
% R    = 0.2;        % Rolloff
DT   = 'sqrt';     % Design Type
% DT   = 'normal';     % Design Type
Beta = 0.5;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

% [EOF]
